nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/musique/download':
            skip_same_as_origin: false
            allow_origin: ['*']
            allow_methods: ['GET']
            allow_headers: ['Authorization']
            # Pas de modification de la réponse binaire
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600
